version: '3'

services:

  # --- Notes Service ---

  notes-service:
    image: eposgmbh/notes-webapi:latest
    restart: always
    build: ../src/services/notes
    entrypoint: >
      /svc/wait-for-it.sh --strict --timeout=30 postgres:5432 --
      /svc/wait-for-it.sh --strict --timeout=30 rabbitmq:5672 --
      dotnet Notes.WebApi.dll
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - rabbitmq

  message-broadcast-service:
    image: eposgmbh/message-broadcast:latest
    restart: always
    build: ../src/services/message-broadcast/MessageBroadcast.WebApi
    entrypoint: >
      /svc/wait-for-it.sh --strict --timeout=30 notes-service:5000 --
      dotnet MessageBroadcast.WebApi.dll
    ports:
      - 5001:5001
    depends_on:
      - notes-service

  notes-api-gateway:
    image: eposgmbh/notes-api-gateway:latest
    restart: always
    build: ../src/apps/notes/Notes.ApiGateway
    entrypoint: >
      /svc/wait-for-it.sh --strict --timeout=30 notes-service:5000 --
      dotnet Notes.ApiGateway.dll
    ports:
      - 4000:4000
    depends_on:
      - notes-service

  notes-spa:
    image: eposgmbh/notes-spa:latest
    restart: always
    build: ../src/apps/notes/Notes.Spa
    entrypoint: >
      /wait-for-it.sh --strict --timeout=30 notes-api-gateway:4000 --
      nginx -g "daemon off;"
    ports:
      - 80:80
    depends_on:
      - notes-api-gateway
