version: '3'

services:
  notes-service:
    image: eposgmbh/notes-webapi:latest
    restart: always
    build: ../src/services/notes
    entrypoint: >
      /svc/wait-for-it.sh --strict --timeout=30 postgres:5432 --
      /svc/wait-for-it.sh --strict --timeout=30 rabbitmq:5672 --
      dotnet Notes.WebApi.dll
    ports:
      - 80:80
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JklM8765
    ports:
      - 5432:5432

  postgres-admin:
    image: fenglc/pgadmin4
    restart: always
    volumes:
      - postgres-admin-data:/var/lib/pgadmin
    ports:
      - 5050:5050
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq
    restart: always
    hostname: rabbitmq-host
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672

volumes:
  postgres-data:
  postgres-admin-data:
  rabbitmq-data:
